### ISSUE TITLE
Modify the readme file

### ISSUE THREAD

**Issue by isuruamantha** [isuruamantha/Leave-Management#1]

**Comment by shwetaudacious** [comment]
Can you give a brief description of expected modification?

**Comment by HassanKhanKhan** [comment]
sir login isnt responce please tell me how can i

**Comment by isuruamantha** [comment]
@HassanKhanKhan What's the error you're getting?

**Comment by isuruamantha** [comment]
Closing the issue since @HassanKhanKhan didn't respond back
